# Generated by Django 4.2.7 on 2023-11-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=8)),
                ('qtd_registros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_linha', models.CharField(max_length=1)),
                ('numeracao_lote', models.CharField(max_length=6)),
                ('numero_cartao', models.CharField(max_length=18)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.lote')),
            ],
        ),
    ]
